In [3]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
[1,2,3] * [4,5,6]

TypeError: can't multiply sequence by non-int of type 'list'

# Numerical Python (Numpy)

In [3]:
import numpy as np

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
a * 3

array([3, 6, 9])

# Math Functions

In [8]:
np.sum(a)

6

In [9]:
np.mean(a)

2.0

In [10]:
np.std(a)

0.816496580927726

In [11]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# arange, linspace, logspace

In [26]:
np.arange(0,5,1.5)

array([0. , 1.5, 3. , 4.5])

In [28]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
np.logspace(-3,3,7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random

In [65]:
np.random.rand(3,2)

array([[0.53822452, 0.41610964],
       [0.59529564, 0.65449706],
       [0.5022295 , 0.97696406]])

# Controlled Randomness

In [72]:
state = np.random.RandomState(42)
state.random(3)

array([0.37454012, 0.95071431, 0.73199394])